spring:
  application:
    name: dualeasy-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dualeasy_service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  kafka:
    bootstrap-servers: localhost:9092
    security:
      protocol: SASL_PLAINTEXT
    properties:
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: >
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="admin"
        password="admin-secret";

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: dualeasy-rating
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: gr.project.dualeasy.data.dto.RatingUpdateEvent

    listener:
      type: single
      ack-mode: record


server:
  port: 8090
